name = "mcp-shop-cloudflare"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "ORDERS"
id = "8f632b0982bf4095865617a0f0a34bde" 

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "c88df7006fb64c1faccb42c37b2bdd06"

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "McpShopServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["McpShopServer"]
